//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludVida.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imc
    {
        public int id { get; set; }
        public double height { get; set; }
        public double weight { get; set; }
        public double imcResult { get; set; }
        public string diagnosis { get; set; }
        public string cliente_document { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
